- name: Install Redis
  ansible.builtin.dnf:
    name:
      - redis
    state: present

- name: Create Redis data directory
  ansible.builtin.file:
    path: "{{ redis_data_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: '0750'

- name: Restore SELinux context on Redis data dir
  ansible.builtin.command: restorecon -Rv {{ redis_data_dir }}
  changed_when: false
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: Deploy Redis configuration
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: '0644'
  register: redis_conf

- name: Restart Redis immediately if config changed
  ansible.builtin.systemd:
    name: redis
    state: restarted
    daemon_reload: yes
  when: redis_conf is changed

- name: Ensure Redis is enabled and running
  ansible.builtin.service:
    name: redis
    enabled: true
    state: started

- name: Verify Redis is using expected dir
  ansible.builtin.command: >
    redis-cli -h {{ redis_bind_ip }} -p {{ redis_port }}
    {% if redis_requirepass | length > 0 %}-a {{ redis_requirepass }}{% endif %}
    CONFIG GET dir
  register: redis_dir
  changed_when: false
  failed_when: "'{{ redis_data_dir }}' not in redis_dir.stdout"

- name: Wait for Redis port to be open on controller
  ansible.builtin.wait_for:
    host: "{{ redis_bind_ip }}"
    port: "{{ redis_port }}"
    timeout: 10

- name: Verify Redis is listening
  ansible.builtin.command: "ss -lntp sport = :{{ redis_port }}"
  register: ss_listen
  changed_when: false
  failed_when: ss_listen.rc !=0 or ss_listen.stdout == ""

- name: Ping Redis (local, with auth if set)
  ansible.builtin.command: >
    redis-cli
    -h {{ redis_bind_ip }}
    -p {{ redis_port }}
    {% if redis_requirepass | length > 0 %}
    -a {{ redis_requirepass }}
    {% endif %}
    ping
  register: redis_ping
  changed_when: false
  failed_when: redis_ping.stdout is not search("PONG")