- name: Ensure celery worker service unit is installed
  ansible.builtin.template:
    src: celery-worker.service.j2
    dest: /etc/systemd/system/celery-worker.service
    owner: root
    group: root
    mode: '0644'
  
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

# Change to always restart
- name: Ensure and start celery worker service
  ansible.builtin.systemd:
    name: celery-worker.service
    enabled: true
    state: started