pipeline_root: "/home/almalinux/protein_pipeline"
pipeline_code_dir: "{{ pipeline_root }}/code"
pipeline_tools_dir: "{{ pipeline_root }}/tools"
pipeline_data_dir: "{{ pipeline_root }}/data"
pipeline_venv_dir: "{{ pipeline_root }}/venv"
pipeline_runs_dir: "{{ pipeline_root }}/runs"

repo_dir: "/home/almalinux/eda-cw"

ansible_python_interpreter: /usr/bin/python3

# Worker Python dependencies
worker_python_deps:
  - biopython
  - numpy
  - scipy
  - torch
  - celery
  - redis

# Controller Python dependencies
controller_python_deps:
  - biopython
  - celery
  - streamlit
  - redis
  
# S4Pred
s4pred_repo: "https://github.com/psipred/s4pred.git"
s4pred_dir: "{{ pipeline_tools_dir }}/s4pred"
s4pred_weights_url: "http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz"

# HHSuite
hhsuite_dir: "{{ pipeline_tools_dir }}/hh-suite"
hhsuite_tar_url: "https://github.com/soedinglab/hh-suite/releases/download/v3.3.0/hhsuite-3.3.0-AVX2-Linux.tar.gz"
hhsuite_tar_path: "{{ hhsuite_dir }}/hhsuite-3.3.0-AVX2-Linux.tar.gz"

pdb70_dir: "{{ pipeline_data_dir }}/pdb70"
pdb70_tar_url: "https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_latest.tar.gz"

# Mouse proteome storage
proteome_fasta_url: "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/Eukaryota/UP000000589/UP000000589_10090.fasta.gz"
proteome_fasta_filename: "UP000000589_10090.fasta"
proteome_fasta_path: "{{ pipeline_data_dir }}/{{ proteome_fasta_filename }}"
proteome_db_path: "{{ pipeline_data_dir }}/mouse_proteome.db"

# Prometheus & Node Exporter configuration
node_exporter_version: "1.7.0"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

prometheus_version: "2.49.1"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

# Redis configuration
redis_host: "controller-node"
redis_port: 6379
redis_requirepass: "imaproteinpipelinerunner"
redis_db: 1
redis_data_dir: "/var/lib/redis"

# Celery configuration 
celery_broker_url: "amqp://admin:abc123@controller-node:5672/protein"
celery_backend_url: "redis://:{{ redis_requirepass }}@{{ redis_host }}:{{ redis_port }}/{{ redis_db }}"
