- hosts: workers
  become: yes
  roles:
    - role: common
      vars:
        python_deps: "{{ worker_python_deps }}"
    - role: code
    - role: s4pred
    - role: hhsuite
    - role: data
    - role: selinux
    - role: celery
    - role: node_exporter
  handlers:
    - name: Restart celery-worker service
      ansible.builtin.systemd:
        name: celery-worker
        state: restarted