- name: Ensure /etc/protein_pipeline exists
  ansible.builtin.file:
    path: /etc/protein_pipeline
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure /runs directory exists
  ansible.builtin.file:
    path: "{{ pipeline_runs_dir }}"
    state: directory
    owner: almalinux
    group: almalinux
    mode: '0755'

- name: Deploy pipeline runctl env file
  ansible.builtin.template:
    src: pipeline.env.j2
    dest: "/etc/protein_pipeline/pipeline.env"
    owner: root
    group: almalinux
    mode: '0640' 

- name: Deploy pp-runctl wrapper script
  ansible.builtin.template:
    src: pp-runctl.j2
    dest: "/usr/local/bin/pp-runctl"
    owner: root
    group: root
    mode: '0755'