- name: Install streamlit systemd service
  ansible.builtin.template:
    src: streamlit.service.j2
    dest: /etc/systemd/system/streamlit.service
    mode: "0644"
  notify: Restart streamlit

- name: Enable and start streamlit service
  ansible.builtin.systemd:
    name: streamlit
    enabled: true
    state: started