- hosts: controller
  become: true
  roles:
    - role: common
      vars:
        python_deps: "{{ controller_python_deps }}"
    - role: code
      vars:
        celery_service: celery-ctl-worker
    - role: clean_up
      vars:
        celery_service: celery-ctl-worker
    - role: rabbitmq
    - role: redis
    - role: pipeline_runctl
    - role: prometheus
    - role: node_exporter
    - role: selinux
    - role: ctl-celery
    - role: streamlit
    - role: ssh-access