- name: Install celery systemd unit
  ansible.builtin.template:
    src: celery-worker.service.j2
    dest: /etc/systemd/system/celery-worker.service
    mode: '0644'
  notify: Restart celery-worker service

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start celery service
  ansible.builtin.systemd:
    name: celery-worker
    enabled: true
    state: started