- name: Copy RabbitMQ repo file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    mode: "0644"

- name: Ensure RabbitMQ dependencies are installed
  ansible.builtin.dnf:
    name:
      - socat
      - logrotate
    state: present

# primary RabbitMQ signing key, modern Erlang repository, RabbitMQ server repository
- name: Copy RabbitMQ/Erlang signing keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/pki/rpm-gpg/{{ item }}"
    mode: "0644"
  loop:
    - "rabbitmq-release-signing-key.asc"
    - "cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
    - "cloudsmith.rabbitmq-server.9F4587F226208342.key"

- name: Import RabbitMQ/Erlang signing keys
  ansible.builtin.rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  loop:
    - "rabbitmq-release-signing-key.asc"
    - "cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
    - "cloudsmith.rabbitmq-server.9F4587F226208342.key"
  register: import_keys
  failed_when: import_keys is failed
  changed_when: import_keys is changed

- name: Ensure Erlang and RabbitMQ are installed
  ansible.builtin.dnf:
    name:  
      - erlang
      - rabbitmq-server
    state: present
    update_cache: true

- name: Enable and start RabbitMQ service
  ansible.builtin.systemd:
    name: rabbitmq-server
    enabled: true
    state: started

- name: Enable RabbitMQ management plugin
  ansible.builtin.command:
    cmd: rabbitmq-plugins enable rabbitmq_management
  args:
    creates: /etc/rabbitmq/enabled_plugins

- name: Ensure RabbitMQ admin user exists
  ansible.builtin.command:
    cmd: rabbitmqctl add_user admin abc123
  register: add_user_result
  failed_when:
    - add_user_result.rc != 0
    - "'already exists' not in add_user_result.stderr"
  changed_when: add_user_result.rc == 0

- name: Get admin user tags
  ansible.builtin.command:
    cmd: rabbitmqctl list_users
  register: user_list
  changed_when: false
  failed_when: user_list.rc != 0

- name: Ensure admin user has administrator tag
  ansible.builtin.command:
    cmd: rabbitmqctl set_user_tags admin administrator
  register: tag_result
  when: >
    not (
      user_list.stdout_lines
        | select('match', '^admin\s+\\[administrator\\]\s*$')
        | list
      )
  failed_when: tag_result.rc != 0
  changed_when: tag_result.rc == 0

# ---- vhost 'protein' ----

- name: Check if vhost 'protein' exists
  ansible.builtin.command:
    cmd: rabbitmqctl list_vhosts
  register: vhosts
  changed_when: false
  failed_when: vhosts.rc != 0

- name: Add dedicated vhost 'protein'
  ansible.builtin.command:
    cmd: rabbitmqctl add_vhost protein
  when: "'protein' not in vhosts.stdout"
  register: add_vhost_result
  failed_when: add_vhost_result.rc != 0
  changed_when: add_vhost_result.rc == 0

# ---- permissions for admin on vhost 'protein' ---- 

- name: Check permissions for admin on vhost 'protein'
  ansible.builtin.command:
    cmd: rabbitmqctl list_permissions -p protein
  register: perms
  changed_when: false
  failed_when: perms.rc != 0

- name: Set admin user permissions on vhost 'protein'
  ansible.builtin.command:
    cmd: rabbitmqctl set_permissions -p protein admin ".*" ".*" ".*"
  when: >
      not (
        perms.stdout_lines
          | select('match', '^admin\s+')
          | list
        )
  register: set_perms_result
  failed_when: set_perms_result.rc != 0
  changed_when: set_perms_result.rc == 0