- name: Install RabbitMQ repo file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    mode: "0644"

- name: Ensure RabbitMQ dependencies are installed
  ansible.builtin.dnf:
    name:
      - socat
      - logrotate
    state: present

# primary RabbitMQ signing key, modern Erlang repository, RabbitMQ server repository
- name: Import RabbitMQ/Erlang signing keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
    - https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key 
    - https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key

- name: Ensure Erlang and RabbitMQ are installed
  ansible.builtin.dnf:
    name:  
      - erlang
      - rabbitmq-server
    state: present
    update_cache: true

- name: Enable and start RabbitMQ service
  ansible.builtin.systemd:
    name: rabbitmq-server
    enabled: true
    state: started

- name: Enable RabbitMQ management plugin
  ansible.builtin.command:
    cmd: rabbitmq-plugins enable rabbitmq_management
  args:
    creates: /etc/rabbitmq/enabled_plugins

- name: Ensure RabbitMQ admin user exists
  ansible.builtin.command:
    cmd: rabbitmqctl add_user admin abc123
  register: add_user_result
  failed_when:
    - add_user_result.rc != 0
    - "'already exists' not in add_user_result.stderr"
  changed_when: add_user_result.rc == 0

- name: Get admin user tags
  ansible.builtin.command:
    cmd: rabbitmqctl list_users
  register: user_list

- name: Ensure admin user has administrator tag
  ansible.builtin.command:
    cmd: rabbitmqctl set_user_tags admin administrator
  register: tag_result
  when: >
    not (
      user_list.stdout_lines
        | select('match', '^admin\s+\\[administrator\\]\s*$')
        | list
      )
  failed_when: tag_result.rc != 0
  changed_when: tag_result.rc == 0